repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v0.7.1
    hooks:
      -   id: check-merge-conflict
      -   id: check-yaml
      -   id: end-of-file-fixer
      -   id: trailing-whitespace
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-mod-tidy
